<a href="https://colab.research.google.com/github/aatiqa-ghazali/Deep_Learning-with-Tensor_Flow/blob/main/Model1(MNIST_data).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


### **TensorFlow 2 quickstart for beginners **

In [ ]:
import tensorflow as tf 

#load_dataset

In [ ]:
mnist=tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test)=mnist.load_data()
#Convert the sample data from integers to floating-point numbers:
x_train=x_train / 255.0
x_test=x_test / 255.0

#Building a ML Model

In [ ]:
model=tf.keras.Sequential([
                           tf.keras.layers.Flatten(input_shape=(28,28)),
                           tf.keras.layers.Dense(128,activation='relu'),
                           tf.keras.layers.Dropout(0.2),
                           tf.keras.layers.Dense(10)
                           
                           ])

In [ ]:
predictions=model(x_train[:1]).numpy()
predictions

array([[-0.04720545, -0.2402462 , -0.00056284,  0.04879511,  0.03114077,
         0.24297646, -0.37628248, -0.01829902,  0.07524966,  0.5480435 ]],
      dtype=float32)

The tf.nn.softmax function converts these logits to probabilities for each class:



In [ ]:
tf.nn.softmax(predictions).numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.09022184, 0.07438325, 0.09452971, 0.09931257, 0.09757465,
        0.12059689, 0.06492252, 0.09286788, 0.1019749 , 0.16361572]],
      dtype=float32)>>

Loss function

In [ ]:
loss_fn=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1],predictions).numpy()

2.1153018

Before you start training, configure and compile the model using Keras Model.compile. Set the optimizer class to adam, set the loss to the loss_fn function you defined earlier, and specify a metric to be evaluated for the model by setting the metrics parameter to accuracy.

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

Train and Evaluate

In [ ]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2975 - accuracy: 0.9137
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1410 - accuracy: 0.9566
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1076 - accuracy: 0.9669
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0861 - accuracy: 0.9737
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0734 - accuracy: 0.9766


Evaluate

In [ ]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 1s - loss: 0.0767 - accuracy: 0.9769 - 659ms/epoch - 2ms/step


[0.07667198777198792, 0.9768999814987183]

For probablity - an additinal step

In [ ]:
probability_model=tf.keras.Sequential([model,tf.keras.layers.Softmax()])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.68390936e-08, 4.82781548e-09, 2.73906862e-05, 2.01607545e-05,
        2.01683722e-12, 1.68870670e-07, 2.63526153e-13, 9.99951005e-01,
        6.05713012e-07, 6.47308525e-07],
       [1.00490695e-07, 8.23917289e-05, 9.99880314e-01, 3.34687393e-05,
        1.08551770e-14, 1.95568487e-06, 1.64195581e-06, 3.05406552e-13,
        6.81799506e-08, 1.41513869e-15],
       [1.38443443e-06, 9.96498704e-01, 1.50492636e-03, 8.12330109e-05,
        3.13841010e-05, 2.64407681e-05, 7.68301834e-05, 1.69247075e-03,
        8.64390240e-05, 1.72217369e-07],
       [9.99788940e-01, 2.13268825e-09, 9.09889350e-05, 4.29471996e-08,
        4.87135480e-07, 3.53155133e-06, 4.13076559e-05, 7.21347824e-05,
        1.67030887e-08, 2.57128818e-06],
       [2.63620291e-06, 8.67664252e-09, 1.90244809e-05, 2.52236205e-08,
        9.98508036e-01, 2.29853555e-07, 1.97809150e-05, 2.13904830e-04,
        5.01332465e-07, 1.23593537e-03]], dtype=float32)>